Feature/subscribe to new study created gdev 366
ghga-de/upload-controller-service pull request #2
Opened 2022-01-04 19:56 UTC by MoritzHahn1337

Title for squash and merge:
```
Subscribe to new-study-created message (GDEV-366, GDEV-284)
```

Description for squash and merge:
```
Subscribed to new-study-created message
Extract file information from message
Write file information to upload-controller database
```

2022-01-04 19:58 UTC, MoritzHahn1337 commented
template_repo needs to adapt the copyright year, then static files won't fail

2022-01-07 13:11 UTC, KerstenBreuer requested changes
Looks very good. Just tests are missing.

2022-01-07 13:11 UTC, KerstenBreuer commented on upload_controller_service/pubsub/subscribe.py
> +    """
```suggestion
def subscribe_new_study_created(config: Config = CONFIG, run_forever: bool = True) -> None:
    """
    Runs a subscribing process for the "new_study_created" topic
    """
```

2022-01-07 13:21 UTC, MoritzHahn1337 commented
Tests will be added in a future PR

2022-01-07 13:37 UTC, KerstenBreuer approved these changes

2022-01-07 13:37 UTC, merged